[package]
name = "use_case_executor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
cmd_handler = { path = "../../common/cmd_handler" }
common_entity = { package = "entity", path = "../../common/entity" }
example_core_use_case = { path = "../use_case" }
example_outbound_adapter = { path = "../outbound_adapter" }

[dev-dependencies]
example_outbound_adapter = { path = "../outbound_adapter", features = ["test-support"] }
rstest = "0.23"

[lints]
workspace = true
