[package]
name = "entity"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
entity_derive = { path = "../entity_derive" }
minstant = "0.1"
serde = { version = "1", features = ["derive"] }
serde-big-array = "0.5"
thiserror = "1"
tracing = "0.1"

[lints]
workspace = true
