[package]
name = "veldra_core_use_case"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
cmd_handler = { path = "../../common/cmd_handler" }
common_entity = { package = "entity", path = "../../common/entity" }
example_core_use_case = { path = "../../example/use_case" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
veldra_core_entity = { path = "../entity" }

[lints]
workspace = true
