[package]
name = "outbound_adapter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bincode = "1.3"
cmd_handler = { path = "../../common/cmd_handler" }
example_core_use_case = { path = "../../example/use_case" }
libmdbx = "0.6"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
veldra_core_entity = { path = "../entity" }
veldra_core_use_case = { path = "../use_case" }

[lints]
workspace = true
