[package]
name = "wallet_behavior"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["serde"]
serde = ["base_types/serde"]

[dependencies]

base_types = { path = "../../../../lib/common/base_types" }
entity_derive = { path = "../../../../lib/common/entity_derive" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"

[lints]
workspace = true
