[package]
name = "example_outbound_adapter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
test-support = []

[dependencies]
cmd_handler = { path = "../../common/cmd_handler" }
example_core_use_case = { path = "../use_case" }
mysql = "24.0"
thiserror = "1"

[lints]
workspace = true
