[package]
name = "hotstuff_use_case_demo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
cmd_handler = { path = "../../common/cmd_handler" }
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
example_core_use_case = { path = "../use_case" }
example_outbound_adapter = { path = "../outbound_adapter", features = ["test-support"] }
hotstuff_rs = { path = "../../common/hotstuff_rs" }
rand_core = { version = "0.6.4", features = ["getrandom"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
use_case_executor = { path = "../use_case_executor" }

[lints]
workspace = true
