[package]
name = "l1_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
alloy-primitives = "0.8"
cmd_handler = { path = "../../common/cmd_handler" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1"


[dev-dependencies]
proptest = "1.6"
prusti-contracts = "0.1.6"
trybuild = "1.0"
criterion = { version = "0.5", features = ["html_reports"] }

[package.metadata.kani.flags]
tests = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
dbg_macro = "deny"
print_stdout = "deny"
print_stderr = "deny"
todo = "deny"
unimplemented = "deny"
disallowed_methods = "deny"
disallowed_types = "deny"
disallowed_macros = "deny"
await_holding_lock = "deny"
undocumented_unsafe_blocks = "deny"
large_futures = "deny"
mutex_atomic = "deny"
mutex_integer = "deny"
rc_mutex = "deny"
mem_forget = "deny"
large_enum_variant = "warn"
large_stack_arrays = "warn"
large_stack_frames = "warn"
result_large_err = "warn"
boxed_local = "warn"
box_collection = "warn"
redundant_allocation = "warn"
vec_init_then_push = "warn"
slow_vector_initialization = "warn"
unnecessary_to_owned = "warn"
redundant_clone = "warn"
iter_overeager_cloned = "warn"
needless_collect = "warn"
iter_over_hash_type = "warn"
