[package]
name = "base_types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
serde = ["dep:serde", "rust_decimal/serde"]

[dependencies]
entity_derive = { path = "../entity_derive" }
#lob_repo = { path = "../lob_repo" }

diff = { path = "../diff" }
rust_decimal = { version = "1.41", features = ["serde"] }
chrono = "0.4.43"
serde = { version = "1.0", features = ["derive"], optional = true }
sealed = "0.6.0"
arrayvec = "0.7"
minstant = "0.1"
# db_repo = { path = "../db_repo" }  # 循环依赖

[lints]
workspace = true
