[package]
name = "diff"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
entity_derive = { path = "../entity_derive" }
serde = { version = "1.0.203", features = ["derive"] }
zerocopy = { version = "0.8.42", features = ["derive"] }

[lints]
workspace = true
