/// Order snapshot stored after a spot order is accepted.
///
/// The stored order keeps the business facts needed by later workflows such as
/// order cancellation, matching, or account-reservation reconciliation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StoredOrder {
    /// Stable order id generated by the place-order use case.
    pub order_id: String,
    /// Trader account that owns this order and its reserved quote balance.
    pub account_id: String,
    /// Market symbol this order trades, for example `BTCUSDT`.
    pub symbol: String,
    /// Base-asset quantity requested by the order.
    pub qty: u64,
    /// Limit price in quote units.
    pub price: u64,
    /// Quote balance reserved from the account when the order was accepted.
    pub reserved_quote: u64,
}

impl StoredOrder {
    /// Builds a stored order from already validated business facts.
    ///
    /// Validation belongs to the use case that accepts the order. This constructor
    /// deliberately does not reject inconsistent values so adapters can rebuild
    /// historical snapshots from persisted events.
    pub fn new(
        order_id: String,
        account_id: String,
        symbol: String,
        qty: u64,
        price: u64,
        reserved_quote: u64,
    ) -> Self {
        Self { order_id, account_id, symbol, qty, price, reserved_quote }
    }

    /// Returns whether this order is owned by the given account.
    pub fn belongs_to_account(&self, account_id: &str) -> bool {
        self.account_id == account_id
    }

    /// Returns whether this order trades the given market symbol.
    pub fn trades_symbol(&self, symbol: &str) -> bool {
        self.symbol == symbol
    }

    /// Computes the quote notional as `qty * price`.
    ///
    /// Returns `None` when the multiplication overflows.
    pub fn notional_quote(&self) -> Option<u64> {
        self.qty.checked_mul(self.price)
    }

    /// Returns whether the reserved quote matches the order notional.
    pub fn has_consistent_reserved_quote(&self) -> bool {
        self.notional_quote() == Some(self.reserved_quote)
    }

    /// Returns the quote balance that should be released when the order is canceled.
    pub fn quote_to_release_on_cancel(&self) -> u64 {
        self.reserved_quote
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_order() -> StoredOrder {
        StoredOrder::new(
            "order-1".to_string(),
            "trader-1".to_string(),
            "BTCUSDT".to_string(),
            2,
            100,
            200,
        )
    }

    #[test]
    fn new_stores_order_fields() {
        let order = sample_order();

        assert_eq!(order.order_id, "order-1");
        assert_eq!(order.account_id, "trader-1");
        assert_eq!(order.symbol, "BTCUSDT");
        assert_eq!(order.qty, 2);
        assert_eq!(order.price, 100);
        assert_eq!(order.reserved_quote, 200);
    }

    #[test]
    fn checks_order_owner_and_symbol() {
        let order = sample_order();

        assert!(order.belongs_to_account("trader-1"));
        assert!(!order.belongs_to_account("trader-2"));
        assert!(order.trades_symbol("BTCUSDT"));
        assert!(!order.trades_symbol("ETHUSDT"));
    }

    #[test]
    fn derives_notional_quote() {
        let order = sample_order();

        assert_eq!(order.notional_quote(), Some(200));
        assert!(order.has_consistent_reserved_quote());
    }

    #[test]
    fn detects_inconsistent_reserved_quote() {
        let order = StoredOrder::new(
            "order-1".to_string(),
            "trader-1".to_string(),
            "BTCUSDT".to_string(),
            2,
            100,
            199,
        );

        assert!(!order.has_consistent_reserved_quote());
    }

    #[test]
    fn derives_quote_to_release_on_cancel() {
        let order = sample_order();

        assert_eq!(order.quote_to_release_on_cancel(), 200);
    }
}
