use common_entity::{Entity, EntityError, EntityFieldChange};

const STORED_ORDER_ENTITY_TYPE: u8 = 2;

/// Order snapshot stored after a spot order is accepted.
///
/// The stored order keeps the business facts needed by later workflows such as
/// order cancellation, matching, or account-reservation reconciliation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StoredOrder {
    /// Stable order id generated by the place-order use case.
    pub order_id: String,
    /// Trader account that owns this order and its reserved quote balance.
    pub account_id: String,
    /// Market symbol this order trades, for example `BTCUSDT`.
    pub symbol: String,
    /// Base-asset quantity requested by the order.
    pub qty: u64,
    /// Limit price in quote units.
    pub price: u64,
    /// Quote balance reserved from the account when the order was accepted.
    pub reserved_quote: u64,
}

impl StoredOrder {
    /// Builds a stored order from already validated business facts.
    ///
    /// Validation belongs to the use case that accepts the order. This constructor
    /// deliberately does not reject inconsistent values so adapters can rebuild
    /// historical snapshots from persisted events.
    pub fn new(
        order_id: String,
        account_id: String,
        symbol: String,
        qty: u64,
        price: u64,
        reserved_quote: u64,
    ) -> Self {
        Self { order_id, account_id, symbol, qty, price, reserved_quote }
    }

    /// Returns whether this order is owned by the given account.
    pub fn belongs_to_account(&self, account_id: &str) -> bool {
        self.account_id == account_id
    }

    /// Returns whether this order trades the given market symbol.
    pub fn trades_symbol(&self, symbol: &str) -> bool {
        self.symbol == symbol
    }

    /// Computes the quote notional as `qty * price`.
    ///
    /// Returns `None` when the multiplication overflows.
    pub fn notional_quote(&self) -> Option<u64> {
        self.qty.checked_mul(self.price)
    }

    /// Returns whether the reserved quote matches the order notional.
    pub fn has_consistent_reserved_quote(&self) -> bool {
        self.notional_quote() == Some(self.reserved_quote)
    }

    /// Returns the quote balance that should be released when the order is canceled.
    pub fn quote_to_release_on_cancel(&self) -> u64 {
        self.reserved_quote
    }
}

impl Entity for StoredOrder {
    type Id = String;

    fn entity_id(&self) -> Self::Id {
        self.order_id.clone()
    }

    fn entity_type() -> u8 {
        STORED_ORDER_ENTITY_TYPE
    }

    fn entity_version(&self) -> u64 {
        1
    }

    fn created_field_changes(&self) -> Vec<EntityFieldChange> {
        let mut changes = vec![
            EntityFieldChange::new("order_id", "", self.order_id.clone()),
            EntityFieldChange::new("account_id", "", self.account_id.clone()),
            EntityFieldChange::new("symbol", "", self.symbol.clone()),
            EntityFieldChange::new("qty", "", self.qty.to_string()),
            EntityFieldChange::new("price", "", self.price.to_string()),
            EntityFieldChange::new("reserved_quote", "", self.reserved_quote.to_string()),
        ];

        if let Some(order_sequence) = self.order_sequence_from_id() {
            changes.push(EntityFieldChange::new("order_sequence", "", order_sequence.to_string()));
        }

        changes
    }

    fn diff(&self, other: &Self) -> Vec<EntityFieldChange> {
        let mut changes = Vec::new();

        if self.account_id != other.account_id {
            changes.push(EntityFieldChange::new(
                "account_id",
                self.account_id.clone(),
                other.account_id.clone(),
            ));
        }

        if self.symbol != other.symbol {
            changes.push(EntityFieldChange::new(
                "symbol",
                self.symbol.clone(),
                other.symbol.clone(),
            ));
        }

        if self.qty != other.qty {
            changes.push(EntityFieldChange::new(
                "qty",
                self.qty.to_string(),
                other.qty.to_string(),
            ));
        }

        if self.price != other.price {
            changes.push(EntityFieldChange::new(
                "price",
                self.price.to_string(),
                other.price.to_string(),
            ));
        }

        if self.reserved_quote != other.reserved_quote {
            changes.push(EntityFieldChange::new(
                "reserved_quote",
                self.reserved_quote.to_string(),
                other.reserved_quote.to_string(),
            ));
        }

        changes
    }

    fn replay_field_type(field_name: &str) -> u8 {
        match field_name {
            "order_id" | "account_id" | "symbol" => 0,
            "order_sequence" | "qty" | "price" | "reserved_quote" => 1,
            _ => 0,
        }
    }

    fn replay_entity_id(&self) -> Result<i64, EntityError> {
        Ok(stable_order_entity_id(&self.order_id))
    }
}

impl StoredOrder {
    fn order_sequence_from_id(&self) -> Option<u64> {
        self.order_id.rsplit('-').next()?.parse::<u64>().ok()
    }
}

fn stable_order_entity_id(value: &str) -> i64 {
    use std::hash::{Hash, Hasher};

    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    value.hash(&mut hasher);
    (hasher.finish() & i64::MAX as u64) as i64
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_order() -> StoredOrder {
        StoredOrder::new(
            "order-1".to_string(),
            "trader-1".to_string(),
            "BTCUSDT".to_string(),
            2,
            100,
            200,
        )
    }

    #[test]
    fn new_stores_order_fields() {
        let order = sample_order();

        assert_eq!(order.order_id, "order-1");
        assert_eq!(order.account_id, "trader-1");
        assert_eq!(order.symbol, "BTCUSDT");
        assert_eq!(order.qty, 2);
        assert_eq!(order.price, 100);
        assert_eq!(order.reserved_quote, 200);
    }

    #[test]
    fn checks_order_owner_and_symbol() {
        let order = sample_order();

        assert!(order.belongs_to_account("trader-1"));
        assert!(!order.belongs_to_account("trader-2"));
        assert!(order.trades_symbol("BTCUSDT"));
        assert!(!order.trades_symbol("ETHUSDT"));
    }

    #[test]
    fn derives_notional_quote() {
        let order = sample_order();

        assert_eq!(order.notional_quote(), Some(200));
        assert!(order.has_consistent_reserved_quote());
    }

    #[test]
    fn detects_inconsistent_reserved_quote() {
        let order = StoredOrder::new(
            "order-1".to_string(),
            "trader-1".to_string(),
            "BTCUSDT".to_string(),
            2,
            100,
            199,
        );

        assert!(!order.has_consistent_reserved_quote());
    }

    #[test]
    fn derives_quote_to_release_on_cancel() {
        let order = sample_order();

        assert_eq!(order.quote_to_release_on_cancel(), 200);
    }
}
