// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config() -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder.name("xdp_hello_bpf").map("xdp_events", false).map("xdp_hell.rodata", false).prog("xdp_hello");
        builder.build()
    }
    pub struct OpenXdpHelloMaps<'obj> {
        pub xdp_events: libbpf_rs::OpenMapMut<'obj>,
        pub rodata: libbpf_rs::OpenMapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenXdpHelloMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>, object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut xdp_events = None;
            let mut rodata = None;
            let object =
                unsafe { std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(object) };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(std::io::ErrorKind::InvalidData, "map has invalid name"))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "xdp_events" => xdp_events = Some(map),
                    "xdp_hell.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                xdp_events: xdp_events.expect("map `xdp_events` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct XdpHelloMaps<'obj> {
        pub xdp_events: libbpf_rs::MapMut<'obj>,
        pub rodata: libbpf_rs::MapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> XdpHelloMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>, object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut xdp_events = None;
            let mut rodata = None;
            let object = unsafe { std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object) };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(std::io::ErrorKind::InvalidData, "map has invalid name"))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "xdp_events" => xdp_events = Some(map),
                    "xdp_hell.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                xdp_events: xdp_events.expect("map `xdp_events` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenXdpHelloProgs<'obj> {
        pub xdp_hello: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenXdpHelloProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut xdp_hello = None;
            let object =
                unsafe { std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(object) };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "xdp_hello" => xdp_hello = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                xdp_hello: xdp_hello.expect("prog `xdp_hello` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct XdpHelloProgs<'obj> {
        pub xdp_hello: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> XdpHelloProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenXdpHelloProgs<'obj>) -> Self {
            Self {
                xdp_hello: unsafe { libbpf_rs::ProgramMut::new_mut(open_progs.xdp_hello.as_libbpf_object().as_mut()) },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self { object: Some(object) }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct XdpHelloSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> XdpHelloSkelBuilder {
        fn open_opts_impl(
            self, open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenXdpHelloSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret = unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenXdpHelloSkel {
                maps: unsafe { OpenXdpHelloMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenXdpHelloProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for XdpHelloSkelBuilder {
        type Output = OpenXdpHelloSkel<'obj>;
        fn open(
            self, object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenXdpHelloSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self, open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenXdpHelloSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 27],
            pub max_entries: *mut [i32; 8192],
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self { r#type: std::ptr::null_mut(), max_entries: std::ptr::null_mut() }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct xdp_md {
            pub data: u32,
            pub data_end: u32,
            pub data_meta: u32,
            pub ingress_ifindex: u32,
            pub rx_queue_index: u32,
            pub egress_ifindex: u32,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct ethhdr {
            pub h_dest: [u8; 6],
            pub h_source: [u8; 6],
            pub h_proto: u16,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct iphdr {
            pub __pad_0: [u8; 1],
            pub tos: u8,
            pub tot_len: u16,
            pub id: u16,
            pub frag_off: u16,
            pub ttl: u8,
            pub protocol: u8,
            pub check: u16,
            pub __anon_2: __anon_2,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_2 {
            pub __anon_3: __anon_3,
            pub addrs: __anon_3,
        }
        impl std::fmt::Debug for __anon_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_2 {
            fn default() -> Self {
                Self { __anon_3: __anon_3::default() }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_3 {
            pub saddr: u32,
            pub daddr: u32,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct tcphdr {
            pub source: u16,
            pub dest: u16,
            pub seq: u32,
            pub ack_seq: u32,
            pub __pad_12: [u8; 2],
            pub window: u16,
            pub check: u16,
            pub urg_ptr: u16,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct udphdr {
            pub source: u16,
            pub dest: u16,
            pub len: u16,
            pub check: u16,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub xdp_events: __anon_1,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {}
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub _license: [i8; 4],
        }
    }
    pub struct OpenXdpHelloSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenXdpHelloMaps<'obj>,
        pub progs: OpenXdpHelloProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenXdpHelloSkel<'obj> {
        type Output = XdpHelloSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<XdpHelloSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(XdpHelloSkel {
                maps: unsafe { XdpHelloMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: XdpHelloProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: XdpHelloLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct XdpHelloLinks {
        pub xdp_hello: Option<libbpf_rs::Link>,
    }
    pub struct XdpHelloSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: XdpHelloMaps<'obj>,
        pub progs: XdpHelloProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: XdpHelloLinks,
    }

    unsafe impl Send for XdpHelloSkel<'_> {}
    unsafe impl Sync for XdpHelloSkel<'_> {}

    impl<'obj> Skel<'obj> for XdpHelloSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = XdpHelloLinks {
                xdp_hello: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl XdpHelloSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 192, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 64, 0, 10, 0, 1, 0, 0, 46, 115, 116,
        114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97, 98, 0, 120, 100, 112, 0, 46, 109, 97, 112, 115, 0, 46, 114,
        111, 100, 97, 116, 97, 0, 108, 105, 99, 101, 110, 115, 101, 0, 120, 100, 112, 95, 104, 101, 108, 108, 111, 46,
        98, 112, 102, 46, 99, 0, 120, 100, 112, 95, 104, 101, 108, 108, 111, 46, 95, 95, 95, 95, 102, 109, 116, 0, 120,
        100, 112, 95, 104, 101, 108, 108, 111, 0, 120, 100, 112, 95, 101, 118, 101, 110, 116, 115, 0, 95, 108, 105, 99,
        101, 110, 115, 101, 0, 46, 114, 101, 108, 120, 100, 112, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120,
        116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 0, 0,
        0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 3, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 77, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 184, 2, 0, 0, 0, 0, 0, 0, 87, 0, 0, 0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 98, 0,
        0, 0, 17, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 97, 24, 4, 0, 0, 0, 0, 0, 97, 23, 0, 0, 0,
        0, 0, 0, 191, 121, 0, 0, 0, 0, 0, 0, 7, 9, 0, 0, 14, 0, 0, 0, 45, 137, 80, 0, 0, 0, 0, 0, 105, 114, 12, 0, 0,
        0, 0, 0, 85, 2, 74, 0, 8, 0, 0, 0, 191, 114, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 34, 0, 0, 0, 45, 130, 75, 0, 0, 0,
        0, 0, 113, 146, 9, 0, 0, 0, 0, 0, 85, 2, 13, 0, 6, 0, 0, 0, 113, 146, 0, 0, 0, 0, 0, 0, 103, 2, 0, 0, 2, 0, 0,
        0, 87, 2, 0, 0, 60, 0, 0, 0, 191, 147, 0, 0, 0, 0, 0, 0, 15, 35, 0, 0, 0, 0, 0, 0, 191, 50, 0, 0, 0, 0, 0, 0,
        7, 2, 0, 0, 20, 0, 0, 0, 45, 130, 65, 0, 0, 0, 0, 0, 183, 4, 0, 0, 2, 0, 0, 0, 191, 50, 0, 0, 0, 0, 0, 0, 15,
        66, 0, 0, 0, 0, 0, 0, 105, 51, 0, 0, 0, 0, 0, 0, 5, 0, 16, 0, 0, 0, 0, 0, 183, 4, 0, 0, 0, 0, 0, 0, 113, 146,
        9, 0, 0, 0, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 85, 2, 15, 0, 17, 0, 0, 0, 113, 146, 0, 0, 0, 0, 0, 0, 103, 2, 0,
        0, 2, 0, 0, 0, 87, 2, 0, 0, 60, 0, 0, 0, 191, 147, 0, 0, 0, 0, 0, 0, 15, 35, 0, 0, 0, 0, 0, 0, 191, 50, 0, 0,
        0, 0, 0, 0, 7, 2, 0, 0, 8, 0, 0, 0, 45, 130, 48, 0, 0, 0, 0, 0, 183, 4, 0, 0, 2, 0, 0, 0, 191, 50, 0, 0, 0, 0,
        0, 0, 15, 66, 0, 0, 0, 0, 0, 0, 105, 51, 0, 0, 0, 0, 0, 0, 220, 3, 0, 0, 16, 0, 0, 0, 105, 36, 0, 0, 0, 0, 0,
        0, 220, 4, 0, 0, 16, 0, 0, 0, 123, 74, 240, 255, 0, 0, 0, 0, 123, 58, 248, 255, 0, 0, 0, 0, 191, 22, 0, 0, 0,
        0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 40, 0, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0,
        133, 0, 0, 0, 131, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 191, 6, 0, 0, 0, 0, 0, 0, 21, 6, 26, 0, 0, 0, 0, 0, 123,
        26, 232, 255, 0, 0, 0, 0, 133, 0, 0, 0, 5, 0, 0, 0, 123, 6, 0, 0, 0, 0, 0, 0, 121, 161, 232, 255, 0, 0, 0, 0,
        97, 17, 12, 0, 0, 0, 0, 0, 99, 22, 8, 0, 0, 0, 0, 0, 113, 145, 9, 0, 0, 0, 0, 0, 99, 22, 12, 0, 0, 0, 0, 0, 97,
        145, 12, 0, 0, 0, 0, 0, 99, 22, 16, 0, 0, 0, 0, 0, 97, 145, 16, 0, 0, 0, 0, 0, 99, 22, 20, 0, 0, 0, 0, 0, 31,
        120, 0, 0, 0, 0, 0, 0, 99, 134, 28, 0, 0, 0, 0, 0, 121, 161, 248, 255, 0, 0, 0, 0, 107, 22, 24, 0, 0, 0, 0, 0,
        121, 161, 240, 255, 0, 0, 0, 0, 107, 22, 26, 0, 0, 0, 0, 0, 105, 113, 12, 0, 0, 0, 0, 0, 119, 1, 0, 0, 8, 0, 0,
        0, 115, 22, 32, 0, 0, 0, 0, 0, 105, 113, 12, 0, 0, 0, 0, 0, 115, 22, 33, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0,
        0, 183, 2, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 132, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183,
        2, 0, 0, 16, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 183, 0, 0, 0, 2, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 101, 108, 108, 111, 32, 102, 114, 111, 109, 32, 88, 68, 80, 33, 0, 71,
        80, 76, 0, 0, 0, 0, 0, 120, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 136, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        4, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 112, 4, 0, 0, 112, 4, 0, 0, 76, 7, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0,
        0, 4, 0, 0, 0, 27, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 2, 0, 0, 4, 16, 0, 0,
        0, 25, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0, 42, 0, 0, 0, 0, 0, 0, 14, 7, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 10, 0, 0, 0, 53, 0, 0, 0, 6, 0, 0, 4, 24, 0, 0, 0, 60, 0, 0, 0, 11,
        0, 0, 0, 0, 0, 0, 0, 65, 0, 0, 0, 11, 0, 0, 0, 32, 0, 0, 0, 74, 0, 0, 0, 11, 0, 0, 0, 64, 0, 0, 0, 84, 0, 0, 0,
        11, 0, 0, 0, 96, 0, 0, 0, 100, 0, 0, 0, 11, 0, 0, 0, 128, 0, 0, 0, 115, 0, 0, 0, 11, 0, 0, 0, 160, 0, 0, 0,
        130, 0, 0, 0, 0, 0, 0, 8, 12, 0, 0, 0, 136, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        13, 2, 0, 0, 0, 149, 0, 0, 0, 9, 0, 0, 0, 153, 0, 0, 0, 1, 0, 0, 12, 13, 0, 0, 0, 163, 0, 0, 0, 3, 0, 0, 4, 14,
        0, 0, 0, 170, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 177, 0, 0, 0, 17, 0, 0, 0, 48, 0, 0, 0, 186, 0, 0, 0, 18, 0, 0,
        0, 96, 0, 0, 0, 194, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 16, 0, 0,
        0, 4, 0, 0, 0, 6, 0, 0, 0, 208, 0, 0, 0, 0, 0, 0, 8, 19, 0, 0, 0, 215, 0, 0, 0, 0, 0, 0, 8, 20, 0, 0, 0, 221,
        0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 16, 0, 0, 0, 236, 0, 0, 0, 10, 0, 0, 132, 20, 0, 0, 0, 242, 0, 0, 0, 22, 0, 0,
        0, 0, 0, 0, 4, 246, 0, 0, 0, 22, 0, 0, 0, 4, 0, 0, 4, 254, 0, 0, 0, 22, 0, 0, 0, 8, 0, 0, 0, 2, 1, 0, 0, 18, 0,
        0, 0, 16, 0, 0, 0, 10, 1, 0, 0, 18, 0, 0, 0, 32, 0, 0, 0, 13, 1, 0, 0, 18, 0, 0, 0, 48, 0, 0, 0, 22, 1, 0, 0,
        22, 0, 0, 0, 64, 0, 0, 0, 26, 1, 0, 0, 22, 0, 0, 0, 72, 0, 0, 0, 35, 1, 0, 0, 23, 0, 0, 0, 80, 0, 0, 0, 0, 0,
        0, 0, 24, 0, 0, 0, 96, 0, 0, 0, 41, 1, 0, 0, 0, 0, 0, 8, 16, 0, 0, 0, 46, 1, 0, 0, 0, 0, 0, 8, 19, 0, 0, 0, 0,
        0, 0, 0, 2, 0, 0, 5, 8, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 54, 1, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 0, 0, 4, 8, 0, 0, 0, 60, 1, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 66, 1, 0, 0, 26, 0, 0, 0, 32, 0, 0, 0,
        72, 1, 0, 0, 0, 0, 0, 8, 11, 0, 0, 0, 79, 1, 0, 0, 17, 0, 0, 132, 20, 0, 0, 0, 86, 1, 0, 0, 18, 0, 0, 0, 0, 0,
        0, 0, 93, 1, 0, 0, 18, 0, 0, 0, 16, 0, 0, 0, 98, 1, 0, 0, 26, 0, 0, 0, 32, 0, 0, 0, 102, 1, 0, 0, 26, 0, 0, 0,
        64, 0, 0, 0, 110, 1, 0, 0, 19, 0, 0, 0, 96, 0, 0, 4, 115, 1, 0, 0, 19, 0, 0, 0, 100, 0, 0, 4, 120, 1, 0, 0, 19,
        0, 0, 0, 104, 0, 0, 1, 124, 1, 0, 0, 19, 0, 0, 0, 105, 0, 0, 1, 128, 1, 0, 0, 19, 0, 0, 0, 106, 0, 0, 1, 132,
        1, 0, 0, 19, 0, 0, 0, 107, 0, 0, 1, 136, 1, 0, 0, 19, 0, 0, 0, 108, 0, 0, 1, 140, 1, 0, 0, 19, 0, 0, 0, 109, 0,
        0, 1, 144, 1, 0, 0, 19, 0, 0, 0, 110, 0, 0, 1, 148, 1, 0, 0, 19, 0, 0, 0, 111, 0, 0, 1, 152, 1, 0, 0, 18, 0, 0,
        0, 112, 0, 0, 0, 35, 1, 0, 0, 23, 0, 0, 0, 128, 0, 0, 0, 159, 1, 0, 0, 18, 0, 0, 0, 144, 0, 0, 0, 167, 1, 0, 0,
        4, 0, 0, 4, 8, 0, 0, 0, 86, 1, 0, 0, 18, 0, 0, 0, 0, 0, 0, 0, 93, 1, 0, 0, 18, 0, 0, 0, 16, 0, 0, 0, 174, 1, 0,
        0, 18, 0, 0, 0, 32, 0, 0, 0, 35, 1, 0, 0, 23, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 30, 0, 0, 0, 178,
        1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 29, 0, 0, 0, 4, 0, 0, 0, 16,
        0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 14, 31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 30, 0, 0, 0,
        4, 0, 0, 0, 4, 0, 0, 0, 201, 1, 0, 0, 0, 0, 0, 14, 33, 0, 0, 0, 1, 0, 0, 0, 50, 7, 0, 0, 1, 0, 0, 15, 16, 0, 0,
        0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 56, 7, 0, 0, 1, 0, 0, 15, 16, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 16, 0,
        0, 0, 64, 7, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 34, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 105, 110, 116, 0, 95, 95,
        65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 116, 121, 112, 101, 0, 109, 97, 120, 95,
        101, 110, 116, 114, 105, 101, 115, 0, 120, 100, 112, 95, 101, 118, 101, 110, 116, 115, 0, 120, 100, 112, 95,
        109, 100, 0, 100, 97, 116, 97, 0, 100, 97, 116, 97, 95, 101, 110, 100, 0, 100, 97, 116, 97, 95, 109, 101, 116,
        97, 0, 105, 110, 103, 114, 101, 115, 115, 95, 105, 102, 105, 110, 100, 101, 120, 0, 114, 120, 95, 113, 117,
        101, 117, 101, 95, 105, 110, 100, 101, 120, 0, 101, 103, 114, 101, 115, 115, 95, 105, 102, 105, 110, 100, 101,
        120, 0, 95, 95, 117, 51, 50, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 99, 116, 120, 0,
        120, 100, 112, 95, 104, 101, 108, 108, 111, 0, 101, 116, 104, 104, 100, 114, 0, 104, 95, 100, 101, 115, 116, 0,
        104, 95, 115, 111, 117, 114, 99, 101, 0, 104, 95, 112, 114, 111, 116, 111, 0, 117, 110, 115, 105, 103, 110,
        101, 100, 32, 99, 104, 97, 114, 0, 95, 95, 98, 101, 49, 54, 0, 95, 95, 117, 49, 54, 0, 117, 110, 115, 105, 103,
        110, 101, 100, 32, 115, 104, 111, 114, 116, 0, 105, 112, 104, 100, 114, 0, 105, 104, 108, 0, 118, 101, 114,
        115, 105, 111, 110, 0, 116, 111, 115, 0, 116, 111, 116, 95, 108, 101, 110, 0, 105, 100, 0, 102, 114, 97, 103,
        95, 111, 102, 102, 0, 116, 116, 108, 0, 112, 114, 111, 116, 111, 99, 111, 108, 0, 99, 104, 101, 99, 107, 0, 95,
        95, 117, 56, 0, 95, 95, 115, 117, 109, 49, 54, 0, 97, 100, 100, 114, 115, 0, 115, 97, 100, 100, 114, 0, 100,
        97, 100, 100, 114, 0, 95, 95, 98, 101, 51, 50, 0, 116, 99, 112, 104, 100, 114, 0, 115, 111, 117, 114, 99, 101,
        0, 100, 101, 115, 116, 0, 115, 101, 113, 0, 97, 99, 107, 95, 115, 101, 113, 0, 114, 101, 115, 49, 0, 100, 111,
        102, 102, 0, 102, 105, 110, 0, 115, 121, 110, 0, 114, 115, 116, 0, 112, 115, 104, 0, 97, 99, 107, 0, 117, 114,
        103, 0, 101, 99, 101, 0, 99, 119, 114, 0, 119, 105, 110, 100, 111, 119, 0, 117, 114, 103, 95, 112, 116, 114, 0,
        117, 100, 112, 104, 100, 114, 0, 108, 101, 110, 0, 99, 104, 97, 114, 0, 120, 100, 112, 95, 104, 101, 108, 108,
        111, 46, 95, 95, 95, 95, 102, 109, 116, 0, 95, 108, 105, 99, 101, 110, 115, 101, 0, 47, 97, 112, 112, 47, 97,
        112, 112, 47, 120, 100, 112, 95, 108, 105, 98, 98, 112, 102, 47, 115, 114, 99, 47, 98, 112, 102, 47, 120, 100,
        112, 95, 104, 101, 108, 108, 111, 46, 98, 112, 102, 46, 99, 0, 32, 32, 32, 32, 118, 111, 105, 100, 32, 42, 100,
        97, 116, 97, 95, 101, 110, 100, 32, 61, 32, 40, 118, 111, 105, 100, 32, 42, 41, 40, 108, 111, 110, 103, 41, 99,
        116, 120, 45, 62, 100, 97, 116, 97, 95, 101, 110, 100, 59, 0, 32, 32, 32, 32, 118, 111, 105, 100, 32, 42, 100,
        97, 116, 97, 32, 61, 32, 40, 118, 111, 105, 100, 32, 42, 41, 40, 108, 111, 110, 103, 41, 99, 116, 120, 45, 62,
        100, 97, 116, 97, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40, 40, 118, 111, 105, 100, 32, 42, 41, 101, 116, 104,
        32, 43, 32, 115, 105, 122, 101, 111, 102, 40, 42, 101, 116, 104, 41, 32, 62, 32, 100, 97, 116, 97, 95, 101,
        110, 100, 41, 0, 32, 32, 32, 32, 105, 102, 32, 40, 98, 112, 102, 95, 110, 116, 111, 104, 115, 40, 101, 116,
        104, 45, 62, 104, 95, 112, 114, 111, 116, 111, 41, 32, 61, 61, 32, 69, 84, 72, 95, 80, 95, 73, 80, 41, 32, 123,
        0, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 40, 118, 111, 105, 100, 32, 42, 41, 105, 112, 104, 32, 43,
        32, 115, 105, 122, 101, 111, 102, 40, 42, 105, 112, 104, 41, 32, 62, 32, 100, 97, 116, 97, 95, 101, 110, 100,
        41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 105, 112, 104, 45, 62, 112, 114, 111, 116, 111, 99,
        111, 108, 32, 61, 61, 32, 73, 80, 80, 82, 79, 84, 79, 95, 84, 67, 80, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 115, 116, 114, 117, 99, 116, 32, 116, 99, 112, 104, 100, 114, 32, 42, 116, 99, 112,
        104, 32, 61, 32, 40, 118, 111, 105, 100, 32, 42, 41, 105, 112, 104, 32, 43, 32, 105, 112, 104, 45, 62, 105,
        104, 108, 32, 42, 32, 52, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 40, 118,
        111, 105, 100, 32, 42, 41, 116, 99, 112, 104, 32, 43, 32, 115, 105, 122, 101, 111, 102, 40, 42, 116, 99, 112,
        104, 41, 32, 62, 32, 100, 97, 116, 97, 95, 101, 110, 100, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 115, 114, 99, 95, 112, 111, 114, 116, 32, 61, 32, 98, 112, 102, 95, 110, 116, 111, 104, 115, 40, 116, 99,
        112, 104, 45, 62, 115, 111, 117, 114, 99, 101, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 125, 32, 101, 108,
        115, 101, 32, 105, 102, 32, 40, 105, 112, 104, 45, 62, 112, 114, 111, 116, 111, 99, 111, 108, 32, 61, 61, 32,
        73, 80, 80, 82, 79, 84, 79, 95, 85, 68, 80, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        115, 116, 114, 117, 99, 116, 32, 117, 100, 112, 104, 100, 114, 32, 42, 117, 100, 112, 104, 32, 61, 32, 40, 118,
        111, 105, 100, 32, 42, 41, 105, 112, 104, 32, 43, 32, 105, 112, 104, 45, 62, 105, 104, 108, 32, 42, 32, 52, 59,
        0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 40, 118, 111, 105, 100, 32, 42, 41, 117,
        100, 112, 104, 32, 43, 32, 115, 105, 122, 101, 111, 102, 40, 42, 117, 100, 112, 104, 41, 32, 62, 32, 100, 97,
        116, 97, 95, 101, 110, 100, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 115, 114, 99, 95, 112, 111,
        114, 116, 32, 61, 32, 98, 112, 102, 95, 110, 116, 111, 104, 115, 40, 117, 100, 112, 104, 45, 62, 115, 111, 117,
        114, 99, 101, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 101, 118, 101, 110, 116, 32, 61, 32, 98, 112, 102, 95,
        114, 105, 110, 103, 98, 117, 102, 95, 114, 101, 115, 101, 114, 118, 101, 40, 38, 120, 100, 112, 95, 101, 118,
        101, 110, 116, 115, 44, 32, 115, 105, 122, 101, 111, 102, 40, 42, 101, 118, 101, 110, 116, 41, 44, 32, 48, 41,
        59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 101, 118, 101, 110, 116, 41, 32, 123, 0, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 101, 118, 101, 110, 116, 45, 62, 116, 105, 109, 101, 115, 116, 97, 109,
        112, 32, 61, 32, 98, 112, 102, 95, 107, 116, 105, 109, 101, 95, 103, 101, 116, 95, 110, 115, 40, 41, 59, 0, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 101, 118, 101, 110, 116, 45, 62, 105, 102, 105, 110, 100, 101, 120,
        32, 61, 32, 99, 116, 120, 45, 62, 105, 110, 103, 114, 101, 115, 115, 95, 105, 102, 105, 110, 100, 101, 120, 59,
        0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 101, 118, 101, 110, 116, 45, 62, 112, 114, 111, 116, 111,
        99, 111, 108, 32, 61, 32, 105, 112, 104, 45, 62, 112, 114, 111, 116, 111, 99, 111, 108, 59, 0, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 101, 118, 101, 110, 116, 45, 62, 115, 114, 99, 95, 105, 112, 32, 61, 32, 105,
        112, 104, 45, 62, 115, 97, 100, 100, 114, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 101, 118, 101,
        110, 116, 45, 62, 100, 115, 116, 95, 105, 112, 32, 61, 32, 105, 112, 104, 45, 62, 100, 97, 100, 100, 114, 59,
        0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 101, 118, 101, 110, 116, 45, 62, 112, 107, 116, 95, 108,
        101, 110, 32, 61, 32, 100, 97, 116, 97, 95, 101, 110, 100, 32, 45, 32, 100, 97, 116, 97, 59, 0, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 101, 118, 101, 110, 116, 45, 62, 115, 114, 99, 95, 112, 111, 114, 116, 32, 61,
        32, 115, 114, 99, 95, 112, 111, 114, 116, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 101, 118, 101,
        110, 116, 45, 62, 100, 115, 116, 95, 112, 111, 114, 116, 32, 61, 32, 100, 115, 116, 95, 112, 111, 114, 116, 59,
        0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 101, 118, 101, 110, 116, 45, 62, 101, 116, 104, 95, 112,
        114, 111, 116, 111, 91, 48, 93, 32, 61, 32, 101, 116, 104, 45, 62, 104, 95, 112, 114, 111, 116, 111, 32, 62,
        62, 32, 56, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 101, 118, 101, 110, 116, 45, 62, 101, 116,
        104, 95, 112, 114, 111, 116, 111, 91, 49, 93, 32, 61, 32, 101, 116, 104, 45, 62, 104, 95, 112, 114, 111, 116,
        111, 32, 38, 32, 48, 120, 70, 70, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 114,
        105, 110, 103, 98, 117, 102, 95, 115, 117, 98, 109, 105, 116, 40, 101, 118, 101, 110, 116, 44, 32, 48, 41, 59,
        0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 72, 101, 108, 108, 111, 32, 102,
        114, 111, 109, 32, 88, 68, 80, 33, 34, 41, 59, 0, 125, 0, 48, 58, 49, 0, 48, 58, 48, 0, 48, 58, 50, 0, 48, 58,
        55, 0, 48, 58, 51, 0, 48, 58, 57, 58, 48, 58, 48, 0, 48, 58, 57, 58, 48, 58, 49, 0, 46, 109, 97, 112, 115, 0,
        46, 114, 111, 100, 97, 116, 97, 0, 108, 105, 99, 101, 110, 115, 101, 0, 120, 100, 112, 0, 0, 0, 0, 0, 159, 235,
        1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 12, 3, 0, 0, 32, 3, 0, 0, 28, 1, 0, 0, 8, 0, 0, 0, 72,
        7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 16, 0, 0, 0, 72, 7, 0, 0, 48, 0, 0, 0, 0, 0, 0, 0, 210, 1, 0, 0,
        254, 1, 0, 0, 41, 132, 0, 0, 8, 0, 0, 0, 210, 1, 0, 0, 48, 2, 0, 0, 37, 128, 0, 0, 16, 0, 0, 0, 210, 1, 0, 0,
        90, 2, 0, 0, 21, 148, 0, 0, 32, 0, 0, 0, 210, 1, 0, 0, 90, 2, 0, 0, 9, 148, 0, 0, 40, 0, 0, 0, 210, 1, 0, 0,
        137, 2, 0, 0, 9, 164, 0, 0, 48, 0, 0, 0, 210, 1, 0, 0, 137, 2, 0, 0, 9, 164, 0, 0, 56, 0, 0, 0, 210, 1, 0, 0,
        184, 2, 0, 0, 25, 172, 0, 0, 72, 0, 0, 0, 210, 1, 0, 0, 184, 2, 0, 0, 13, 172, 0, 0, 80, 0, 0, 0, 210, 1, 0, 0,
        235, 2, 0, 0, 18, 200, 0, 0, 88, 0, 0, 0, 210, 1, 0, 0, 235, 2, 0, 0, 13, 200, 0, 0, 96, 0, 0, 0, 210, 1, 0, 0,
        23, 3, 0, 0, 54, 204, 0, 0, 104, 0, 0, 0, 210, 1, 0, 0, 23, 3, 0, 0, 58, 204, 0, 0, 120, 0, 0, 0, 210, 1, 0, 0,
        23, 3, 0, 0, 47, 204, 0, 0, 136, 0, 0, 0, 210, 1, 0, 0, 85, 3, 0, 0, 30, 208, 0, 0, 152, 0, 0, 0, 210, 1, 0, 0,
        85, 3, 0, 0, 17, 208, 0, 0, 184, 0, 0, 0, 210, 1, 0, 0, 142, 3, 0, 0, 24, 216, 0, 0, 208, 0, 0, 0, 210, 1, 0,
        0, 190, 3, 0, 0, 25, 224, 0, 0, 224, 0, 0, 0, 210, 1, 0, 0, 190, 3, 0, 0, 20, 224, 0, 0, 232, 0, 0, 0, 210, 1,
        0, 0, 241, 3, 0, 0, 54, 228, 0, 0, 240, 0, 0, 0, 210, 1, 0, 0, 241, 3, 0, 0, 58, 228, 0, 0, 0, 1, 0, 0, 210, 1,
        0, 0, 241, 3, 0, 0, 47, 228, 0, 0, 16, 1, 0, 0, 210, 1, 0, 0, 47, 4, 0, 0, 30, 232, 0, 0, 32, 1, 0, 0, 210, 1,
        0, 0, 47, 4, 0, 0, 17, 232, 0, 0, 64, 1, 0, 0, 210, 1, 0, 0, 104, 4, 0, 0, 24, 240, 0, 0, 120, 1, 0, 0, 210, 1,
        0, 0, 152, 4, 0, 0, 17, 8, 1, 0, 176, 1, 0, 0, 210, 1, 0, 0, 221, 4, 0, 0, 13, 12, 1, 0, 192, 1, 0, 0, 210, 1,
        0, 0, 242, 4, 0, 0, 32, 16, 1, 0, 200, 1, 0, 0, 210, 1, 0, 0, 242, 4, 0, 0, 30, 16, 1, 0, 208, 1, 0, 0, 210, 1,
        0, 0, 37, 5, 0, 0, 35, 20, 1, 0, 224, 1, 0, 0, 210, 1, 0, 0, 37, 5, 0, 0, 28, 20, 1, 0, 232, 1, 0, 0, 210, 1,
        0, 0, 88, 5, 0, 0, 36, 24, 1, 0, 240, 1, 0, 0, 210, 1, 0, 0, 88, 5, 0, 0, 29, 24, 1, 0, 248, 1, 0, 0, 210, 1,
        0, 0, 133, 5, 0, 0, 34, 28, 1, 0, 0, 2, 0, 0, 210, 1, 0, 0, 133, 5, 0, 0, 27, 28, 1, 0, 8, 2, 0, 0, 210, 1, 0,
        0, 173, 5, 0, 0, 34, 32, 1, 0, 16, 2, 0, 0, 210, 1, 0, 0, 173, 5, 0, 0, 27, 32, 1, 0, 24, 2, 0, 0, 210, 1, 0,
        0, 213, 5, 0, 0, 39, 44, 1, 0, 32, 2, 0, 0, 210, 1, 0, 0, 213, 5, 0, 0, 28, 44, 1, 0, 40, 2, 0, 0, 210, 1, 0,
        0, 3, 6, 0, 0, 29, 36, 1, 0, 56, 2, 0, 0, 210, 1, 0, 0, 43, 6, 0, 0, 29, 40, 1, 0, 72, 2, 0, 0, 210, 1, 0, 0,
        83, 6, 0, 0, 40, 48, 1, 0, 80, 2, 0, 0, 210, 1, 0, 0, 83, 6, 0, 0, 48, 48, 1, 0, 88, 2, 0, 0, 210, 1, 0, 0, 83,
        6, 0, 0, 33, 48, 1, 0, 96, 2, 0, 0, 210, 1, 0, 0, 136, 6, 0, 0, 40, 52, 1, 0, 104, 2, 0, 0, 210, 1, 0, 0, 136,
        6, 0, 0, 33, 52, 1, 0, 112, 2, 0, 0, 210, 1, 0, 0, 191, 6, 0, 0, 13, 56, 1, 0, 136, 2, 0, 0, 210, 1, 0, 0, 233,
        6, 0, 0, 5, 72, 1, 0, 168, 2, 0, 0, 210, 1, 0, 0, 12, 7, 0, 0, 1, 80, 1, 0, 16, 0, 0, 0, 72, 7, 0, 0, 17, 0, 0,
        0, 0, 0, 0, 0, 10, 0, 0, 0, 14, 7, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 10, 0, 0, 0, 18, 7, 0, 0, 0, 0, 0, 0, 40, 0,
        0, 0, 15, 0, 0, 0, 22, 7, 0, 0, 0, 0, 0, 0, 80, 0, 0, 0, 21, 0, 0, 0, 26, 7, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 21,
        0, 0, 0, 18, 7, 0, 0, 0, 0, 0, 0, 160, 0, 0, 0, 27, 0, 0, 0, 14, 7, 0, 0, 0, 0, 0, 0, 184, 0, 0, 0, 27, 0, 0,
        0, 18, 7, 0, 0, 0, 0, 0, 0, 208, 0, 0, 0, 21, 0, 0, 0, 26, 7, 0, 0, 0, 0, 0, 0, 232, 0, 0, 0, 21, 0, 0, 0, 18,
        7, 0, 0, 0, 0, 0, 0, 40, 1, 0, 0, 28, 0, 0, 0, 14, 7, 0, 0, 0, 0, 0, 0, 64, 1, 0, 0, 28, 0, 0, 0, 18, 7, 0, 0,
        0, 0, 0, 0, 216, 1, 0, 0, 10, 0, 0, 0, 30, 7, 0, 0, 0, 0, 0, 0, 232, 1, 0, 0, 21, 0, 0, 0, 26, 7, 0, 0, 0, 0,
        0, 0, 248, 1, 0, 0, 21, 0, 0, 0, 34, 7, 0, 0, 0, 0, 0, 0, 8, 2, 0, 0, 21, 0, 0, 0, 42, 7, 0, 0, 0, 0, 0, 0, 72,
        2, 0, 0, 15, 0, 0, 0, 22, 7, 0, 0, 0, 0, 0, 0, 96, 2, 0, 0, 15, 0, 0, 0, 22, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 129, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0,
        0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 136, 1, 0,
        0, 0, 0, 0, 0, 184, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 21, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 4, 0, 0, 0, 0, 0, 0, 16, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 1, 0, 0, 0,
        2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 4, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 96, 4, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 107, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 104,
        4, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0,
        0, 0, 0, 115, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 136, 4, 0, 0, 0, 0, 0, 0,
        212, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 16, 0, 0, 0, 0, 0, 0, 92, 4, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
